# SPDX-FileCopyrightText: 2022 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterFilter
metadata:
  labels:
    fluentbit.gardener/type: "seed"
  name: extension-shoot-lakom-service-lakom
spec:
  filters:
  - parser:
      keyName: log
      parser: extension-shoot-lakom-service-lakom-parser
      reserveData: true
  match: kubernetes.*extension-shoot-lakom-service*lakom*
