# SPDX-FileCopyrightText: 2022 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gardener-extension-{{ .Values.serviceName }}-logging-config
  namespace: garden
  labels:
    app.kubernetes.io/name: gardener-extension-{{ .Values.serviceName }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: gardener-extension-{{ .Values.serviceName }}
    extensions.gardener.cloud/configuration: logging
data:
  filter-kubernetes.conf: |
    [FILTER]
        Name                parser
        Match               kubernetes.*extension-shoot-lakom-service*lakom*
        Key_Name            log
        Parser              lakomAdmissionControllerParser
        Reserve_Data        True
  parsers.conf: |
    [PARSER]
        Name        lakomAdmissionControllerParser
        Format      json
        Time_Key    ts
